version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            - SA_PASSWORD=Password1234
            - ACCEPT_EULA=Y
        ports:
            - 1433:1433
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8082:80
            - 8083:443
        depends_on:
            - db
        environment:
            #- ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1234
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ./.aspnet/https:/https:ro